apiVersion: v2
name: oura
description: Sync Oura Ring API v2 data into PostgreSQL
type: application
version: 0.2.10
appVersion: "0.2.10"
home: https://github.com/kgrubb/oura-helm-chart
icon: https://kgrubb.github.io/oura-helm-chart/logo.svg
sources:
  - https://github.com/kgrubb/oura-helm-chart
  - https://cloud.ouraring.com/v2/docs
maintainers:
  - name: kgrubb
    email: 8471701+kgrubb@users.noreply.github.com
    url: https://github.com/kgrubb
keywords:
  - oura
  - health
  - postgres
  - grafana
  - cronjob
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: oura-collector
      image: ghcr.io/kgrubb/oura-collector:0.2.10
  artifacthub.io/links: |
    - name: source
      url: https://github.com/kgrubb/oura-helm-chart
    - name: support
      url: https://github.com/kgrubb/oura-helm-chart/issues
  artifacthub.io/signKey: |
    fingerprint: 9D14AFA7672D09B60F1116886551521D24B1ECB3
    url: https://kgrubb.github.io/oura-helm-chart/public.key
