apiVersion: v2
name: oura
description: Sync Oura Ring API v2 data into PostgreSQL
type: application
version: 0.2.6
appVersion: "0.1.0"
home: https://cloud.ouraring.com/v2/docs
icon: https://kgrubb.github.io/oura-helm-chart/logo.svg
sources:
  - https://cloud.ouraring.com/v2/docs
  - https://github.com/kgrubb/oura-helm-chart
maintainers:
  - name: kgrubb
    email: 8471701+kgrubb@users.noreply.github.com
    url: https://github.com/kgrubb
keywords:
  - oura
  - health
  - postgres
  - grafana
  - cronjob
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/kgrubb/oura-helm-chart/issues
    - name: source
      url: https://github.com/kgrubb/oura-helm-chart
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 9D14AFA7672D09B60F1116886551521D24B1ECB3
    url: https://kgrubb.github.io/oura-helm-chart/public.key
