{{- if .Values.backfill.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-backfill" (include "oura.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: backfill
spec:
  ttlSecondsAfterFinished: {{ .Values.backfill.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.backfill.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "oura.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backfill
    spec:
      restartPolicy: Never
      containers:
        {{- include "oura.container" (dict "root" . "name" "backfill" "backfill" true) | nindent 8 }}
      volumes:
        {{- include "oura.volumes" . | nindent 8 }}
{{- end }}
