{{- if .Values.backfill.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-backfill" (include "oura.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: backfill
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.backfill.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.backfill.activeDeadlineSeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oura.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backfill
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "oura.podSpec" (dict "root" . "name" "backfill" "backfill" true) | nindent 6 }}
{{- end }}
