apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oura.configMapName" . }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  collector.py: |
{{ .Files.Get "files/collector.py" | indent 4 }}
  symptom_radar.py: |
{{ .Files.Get "files/symptom_radar.py" | indent 4 }}
