{{- $hookSecrets := eq (include "oura.bootstrapEnabled" .) "true" -}}
{{- if eq (include "oura.createPostgresSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oura.postgresSecretName" . }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  {{- if $hookSecrets }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
  {{- end }}
type: Opaque
stringData:
  {{ .Values.postgres.passwordKey }}: {{ .Values.postgres.password | quote }}
  {{- if include "oura.readOnlyUser" . }}
  {{ include "oura.readOnlyPasswordKey" . }}: {{ .Values.postgres.passwordRo | quote }}
  {{- end }}
{{- end }}
{{- if eq (include "oura.createAuthSecret" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oura.authSecretName" . }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
type: Opaque
stringData:
  {{ .Values.auth.patKey }}: {{ .Values.auth.pat | quote }}
{{- end }}
{{- if eq (include "oura.createAdminSecret" .) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oura.adminSecretName" . }}
  labels:
    {{- include "oura.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-bootstrap
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
stringData:
  {{ .Values.postgres.bootstrap.admin.passwordKey }}: {{ .Values.postgres.bootstrap.admin.password | quote }}
{{- end }}
